# on:
#   push:
#     tags:
#       - v*.*.*

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: Publishing Kelk to crates.io

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/cargo@v1

      - name: docs check
        run: cargo doc --no-deps

      - name: check the crates
        run: pyton3 publish.py check -v

      - name: publish the crates
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: pyton3 publish.py publish --dry-run True -v
